name: Build and Run Gradle project

on:
  push:
  workflow_dispatch:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.2
    - name: Run build with Gradle Wrapper
      run: gradle build
    - name: Run app with Gradle Wrapper
      run: gradle run --stacktrace

